AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: "Nome dell'ambiente destinazione"

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  # CdcKinesisSourceStreamArn:
  #   Type: String
  #   Description: 'Where to send CDC'


Resources:

  PnEcTableAnagrafica:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'cxId'
          AttributeType: 'S'
      KeySchema: 
        - AttributeName: 'cxId'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
        SSEType: 'KMS'
      TableClass: 'STANDARD'
    DeletionPolicy: Retain

  PnEcTableRichieste:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'requestId'
          AttributeType: 'S'
        - AttributeName: 'correlationId'
          AttributeType: 'S'
      KeySchema: 
        - AttributeName: 'requestId'
          KeyType: 'HASH'
        - AttributeName: 'correlationId'
          KeyType: 'RANGE'
      #KinesisStreamSpecification:
      #  StreamArn: 'String'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
        SSEType: 'KMS'
      TableClass: 'STANDARD'
    DeletionPolicy: Retain

  PnEcQueueTrackerStatoSMS:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1      
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt PnEcDLQueueTrackerStatoSMS.Arn
        maxReceiveCount : 10
      VisibilityTimeout: 30

  PnEcDLQueueTrackerStatoSMS:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 30

  PnEcQueueTrackerErroriSMS:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1      
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PnEcDLQueueTrackerErroriSMS.Arn
        maxReceiveCount: 10
      VisibilityTimeout: 30

  PnEcDLQueueTrackerErroriSMS:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 30

  PnEcQueueNotificheExt1:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1      
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt PnEcDLQueueNotificheExt1.Arn
        maxReceiveCount : 10
      VisibilityTimeout: 30

  PnEcDLQueueNotificheExt1:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 30
   
  PnEcSNSNotificheExt1:
    Type: AWS::SNS::Topic
    Properties:
      #DataProtectionPolicy: JSON
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Endpoint: !GetAtt PnEcQueueNotificheExt1.Arn
          Protocol: sqs
  
  PnEcSNSPolicyNotificheExt1:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement: 
          - Action: 
              - 'sns:Publish'
            Effect: 'Allow'
            Principal:  
              Service: 
                - 'events.amazonaws.com'
            Resource: '*'
      Topics: 
        - !Ref PnEcSNSNotificheExt1

  PnEcEventRuleNotificheExt1:
    Type: AWS::Events::Rule
    Properties:
      Description: Description
      EventPattern:   
        source: 
          - 'NOTIFICATION TRACKER'
      State: 'ENABLED'
      Targets:
        - Arn: !Ref PnEcSNSNotificheExt1
          Id: 'TopicTargetForExtNotification'

  PnEcQueueBatchSMS:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1      
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt PnEcDLQueueBatchSMS.Arn
        maxReceiveCount : 10
      VisibilityTimeout: 30

  PnEcDLQueueBatchSMS:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 30
  
  PnEcQueueInteractiveSMS:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1      
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt PnEcDLQueueInteractiveSMS.Arn
        maxReceiveCount : 10
      VisibilityTimeout: 30

  PnEcDLQueueInteractiveSMS:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 30

  PnEcQueueErroriSMS:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1      
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt PnEcDLQueueErroriSMS.Arn
        maxReceiveCount : 10
      VisibilityTimeout: 30

  PnEcDLQueueErroriSMS:
    Type: AWS::SQS::Queue
    Properties:
      KmsDataKeyReusePeriodSeconds: 300
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 30


  PnEcEventBusTrackerExternalNotification: 
    Type: AWS::Events::EventBus
    Properties: 
        Name: 'Pn-Ec-Tracker-Notifications-bus'

Outputs:
  PnEcTableNameAnagrafica:
    Description: "Nome della Tabella DynamoDB relativa all'Anagrafica Client"
    Value: !Ref PnEcTableAnagrafica

  PnEcTableArnAnagrafica:
    Description: "ARN della Tabella DynamoDB relativa all'Anagrafica Client"
    Value: !GetAtt PnEcTableAnagrafica.Arn

  PnEcTableNameRichieste:
    Description: 'Nome della Tabella DynamoDB relativa alle richieste'
    Value: !Ref PnEcTableAnagrafica

  PnEcTableArnRichieste:
    Description: 'ARN della Tabella DynamoDB relativa alle richieste'
    Value: !GetAtt PnEcTableAnagrafica.Arn

  PnEcQueueNameTrackerStatoSMS:
    Description: '[Notification Tracker: canale SMS] Nome della Coda per aggiornamenti di stato afferenti al canale SMS'
    Value: !GetAtt  PnEcQueueTrackerStatoSMS.QueueName

  PnEcQueueArnTrackerStatoSMS:
    Description: '[Notification Tracker: canale SMS] ARN della Coda per aggiornamenti di stato afferenti al canale SMS'
    Value: !GetAtt  PnEcQueueTrackerStatoSMS.Arn

  PnEcQueueUrlTrackerStatoSMS:
    Description: '[Notification Tracker: canale SMS] URL della Coda per aggiornamenti di stato afferenti al canale SMS'
    Value: !Ref  PnEcQueueTrackerStatoSMS

  PnEcDLQueueNameTrackerStatoSMS:
    Description: '[DLQ di Servizio - Tracker] Nome della DLQ relativa alla coda PnEcQueueTrackerStatoSMS'
    Value: !GetAtt  PnEcDLQueueTrackerStatoSMS.QueueName

  PnEcDLQueueArnTrackerStatoSMS:
    Description: '[DLQ di Servizio - Tracker] ARN della DLQ relativa alla coda PnEcQueueTrackerStatoSMS'
    Value: !GetAtt  PnEcDLQueueTrackerStatoSMS.Arn

  PnEcQueueNameTrackerErroriSMS:
    Description: '[Notification Tracker: canale SMS] Nome della Coda Errori afferenti al canale SMS'
    Value: !GetAtt  PnEcQueueTrackerErroriSMS.QueueName

  PnEcQueueArnTrackerErroriSMS:
    Description: '[Notification Tracker: canale SMS] ARN della Coda Errori afferenti al canale SMS'
    Value: !GetAtt  PnEcQueueTrackerErroriSMS.Arn

  PnEcQueueUrlTrackerErroriSMS:
    Description: '[Notification Tracker: canale SMS] URL della Coda Errori afferenti al canale SMS'
    Value: !Ref  PnEcQueueTrackerErroriSMS

  PnEcDLQueueNameTrackerErroriSMS:
    Description: '[DLQ di Servizio - Tracker] Nome della DLQ relativa alla coda PnEcQueueTrackerErroriSMS'
    Value: !GetAtt  PnEcDLQueueTrackerErroriSMS.QueueName

  PnEcDLQueueArnTrackerErroriSMS:
    Description: '[DLQ di Servizio - Tracker] ARN della DLQ relativa alla coda PnEcQueueTrackerErroriSMS'
    Value: !GetAtt  PnEcDLQueueTrackerErroriSMS.Arn

  PnEcQueueNameNotificheExt1:
    Description: '[Notification Tracker: PIATTAFORMA_ESTERNA_1] Nome della Coda per le notifiche a PIATTAFORMA_ESTERNA_1'
    Value: !GetAtt  PnEcQueueNotificheExt1.QueueName

  PnEcQueueArnNotificheExt1:
    Description: '[Notification Tracker: PIATTAFORMA_ESTERNA_1] ARN della Coda per le notifiche a PIATTAFORMA_ESTERNA_1'
    Value: !GetAtt  PnEcQueueNotificheExt1.Arn

  PnEcQueueUrlNotificheExt1:
    Description: '[Notification Tracker: PIATTAFORMA_ESTERNA_1] URL della Coda per le notifiche a PIATTAFORMA_ESTERNA_1'
    Value: !Ref  PnEcQueueNotificheExt1

  PnEcDLQueueNameNotificheExt1:
    Description: '[DLQ di Servizio - Tracker] Nome della DLQ relativa alla coda PnEcQueueNotificheExt1'
    Value: !GetAtt  PnEcDLQueueNotificheExt1.QueueName

  PnEcDLQueueArnNotificheExt1:
    Description: '[DLQ di Servizio - Tracker] ARN della DLQ relativa alla coda PnEcQueueNotificheExt1'
    Value: !GetAtt  PnEcDLQueueNotificheExt1.Arn

  PnEcSNSNameNotificheExt1:
    Description: '[Notification Tracker: Piattaforme esterne] Nome dello SNS Topic per smistare le notifiche alle Piattaforme esterne'
    Value: !GetAtt PnEcSNSNotificheExt1.TopicName

  PnEcSNSArnNotificheExt1:
    Description: '[Notification Tracker: Piattaforme esterne] ARN dello SNS Topic per smistare le notifiche alle Piattaforme esterne'
    Value: !Ref PnEcSNSNotificheExt1

  PnEcQueueNameBatchSMS:
    Description: '[Canale SMS] Nome della Coda per la modalità SMS-Batch'
    Value: !GetAtt  PnEcQueueBatchSMS.QueueName

  PnEcQueueArnBatchSMS:
    Description: '[Canale SMS] ARN della Coda per la modalità SMS-Batch'
    Value: !GetAtt  PnEcQueueBatchSMS.Arn

  PnEcQueueUrlBatchSMS:
    Description: '[Canale SMS] URL della Coda per la modalità SMS-Batch'
    Value: !Ref  PnEcQueueBatchSMS

  PnEcDLQueueNameBatchSMS:
    Description: '[DLQ di Servizio] Nome della DLQ relativa alla coda PnEcQueueBatchSMS'
    Value: !GetAtt  PnEcDLQueueBatchSMS.QueueName

  PnEcDLQueueArnBatchSMS:
    Description: '[DLQ di Servizio] ARN della DLQ relativa alla coda PnEcQueueBatchSMS'
    Value: !GetAtt  PnEcDLQueueBatchSMS.Arn

  PnEcQueueNameInteractiveSMS:
    Description: '[Canale SMS] Nome della Coda per la modalità SMS-Interactive'
    Value: !GetAtt  PnEcQueueInteractiveSMS.QueueName

  PnEcQueueArnInteractiveSMS:
    Description: '[Canale SMS] ARN della Coda per la modalità SMS-Interactive'
    Value: !GetAtt  PnEcQueueInteractiveSMS.Arn

  PnEcQueueUrlInteractiveSMS:
    Description: '[Canale SMS] URL della Coda per la modalità SMS-Interactive'
    Value: !Ref  PnEcQueueInteractiveSMS

  PnEcDLQueueNameInteractiveSMS:
    Description: '[DLQ di Servizio] Nome della DLQ relativa alla coda PnEcQueueInteractiveSMS'
    Value: !GetAtt  PnEcDLQueueInteractiveSMS.QueueName

  PnEcDLQueueArnInteractiveSMS:
    Description: '[DLQ di Servizio] ARN della DLQ relativa alla coda PnEcQueueInteractiveSMS'
    Value: !GetAtt  PnEcDLQueueInteractiveSMS.Arn

  PnEcQueueNameErroriSMS:
    Description: '[Canale SMS] Nome della Coda Errori SMS'
    Value: !GetAtt  PnEcQueueErroriSMS.QueueName

  PnEcQueueArnErroriSMS:
    Description: '[Canale SMS] ARN della Coda Errori SMS'
    Value: !GetAtt  PnEcQueueErroriSMS.Arn

  PnEcQueueUrlErroriSMS:
    Description: '[Canale SMS] URL della Coda Errori SMS'
    Value: !Ref  PnEcQueueErroriSMS

  PnEcDLQueueNameErroriSMS:
    Description: '[DLQ di Servizio] Nome della DLQ relativa alla coda PnEcQueueErroriSMS'
    Value: !GetAtt  PnEcDLQueueErroriSMS.QueueName

  PnEcDLQueueArnErroriSMS:
    Description: '[DLQ di Servizio] ARN della DLQ relativa alla coda PnEcQueueErroriSMS'
    Value: !GetAtt  PnEcDLQueueErroriSMS.Arn