openapi: 3.0.1
info:
  title: Consolidatore ingress API.
  description: >-
    NOTIFICHE DI AVANZAMENTO DEL PROCESSO DI POSTALIZZAZIONE. L'API espone dei servizi sul path "/consolidatore-ingress/v1/".
  version: v1.0
servers:
  - url: >-
      https://api.externalchannel.pagopa.local
    description: Server url
tags:
  - name: PushAttachmentsPreload
    description: Richiesta di pre-caricamento dei documenti da comunicare a PN.
  - name: PushProgressEventsToNotificationPlatform
    description: Webhook con cui PN riceve progressi postalizzazioni

paths:
  /consolidatore-ingress/v1/attachement-preload:
    post:
      summary: Richiesta di pre-caricamento dei documenti da comunicare a PN
      description: |-
        Operazione che richiede a Piattaforma Notifica le informazioni e le autorizzazioni necessarie 
        a precaricare uno o più file.
      tags:
        - PushAttachmentsPreload
      operationId: presignedUploadRequest
      requestBody:
        content:
          application/json:
            schema:
              title: PreLoadRequestSchema
              type: object
              required:
                - preloads
              properties:
                preloads:
                  type: array
                  items:
                    $ref: "#/components/schemas/PreLoadRequest"
                  minItems: 1
                  maxItems: 15
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: PreLoadResponseSchema
                type: object
                required:
                  - preloads
                properties:
                  preloads:
                    type: array
                    items:
                      $ref: "#/components/schemas/PreLoadResponse"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResultCodeResponse'
              examples:
                syntaxError:
                  summary: 'Errore sintattico'
                  value: { resultCode: '400.01', resultDescription: 'Syntax Error', errorList: [ 'field requestId is required' ], clientResponseTimeStamp: '2019-08-24T14:15:22Z' }
                semanticError:
                  summary: 'Errore semantico'
                  value: { resultCode: '400.02', resultDescription: 'Semantic Error', errorList: [ 'unrecognized product Type' ], clientResponseTimeStamp: '2019-08-24T14:15:22Z' }
 
  /consolidatore-ingress/v1/push-progress-events/:
    post:
      operationId: sendPaperProgressStatusRequest
      summary: Webhook con cui PN riceve progressi postalizzazioni
      description: |-
        inserire
      tags:
        - PushProgressEventsToNotificationPlatform
      parameters:
        - $ref: '#/components/parameters/xPagopaExtchServiceId'
        - $ref: '#/components/parameters/xPagopaExtchApiKey'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                $ref: '#/components/schemas/PaperProgressStatusEvent'
        required: true
      responses:
        '202':
          description: >-
            OK, l'evento è stato registrato
          content:
            application/json:
              example: { resultCode: '202.00', resultDescription: 'Accepted', clientResponseTimeStamp: '2019-08-24T14:15:22Z'}
              schema:
                $ref: '#/components/schemas/OperationResultCodeResponse'
        '400':
          description: >- 
            Il ricevente ha eseguito la validazione sintattica o semantica dei campi e 
            tale validazione è fallita: possiblie mismatch di versione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResultCodeResponse'
              examples: 
                syntaxError: 
                  summary: 'Errore sintattico'
                  value: { resultCode: '400.01', resultDescription: 'Syntax Error', errorList: [ 'field requestId is required'], clientResponseTimeStamp: '2019-08-24T14:15:22Z'}
                semanticError: 
                  summary: 'Errore semantico'
                  value: { resultCode: '400.02', resultDescription: 'Semantic Error', errorList: [ 'unrecognized product Type'], clientResponseTimeStamp: '2019-08-24T14:15:22Z'}  
        '401':
          description: >- 
            Il sistema chiamante non è stato identificato, verificare le configurazioni
          content:
            application/json:
              example: { resultCode: '401.00', resultDescription: 'Authentication Failed', clientResponseTimeStamp: '2019-08-24T14:15:22Z'}
              schema:
                $ref: '#/components/schemas/OperationResultCodeResponse' 

components:
  parameters:
    xPagopaExtchServiceId:
      name: x-pagopa-extch-service-id
      description: Identificativo con cui Piattaforma Notifiche si identifica
      in: header
      required: true
      schema:
        type: string
    xPagopaExtchApiKey:
      name: x-api-key
      description: Credenziale di accesso
      in: header
      required: true
      schema:
        type: string
  schemas:
    PreLoadRequest:
      $ref: 'consolidatore-v1.yml#/components/schemas/PreLoadRequest'
    PreLoadResponse:
      $ref: 'consolidatore-v1.yml#/components/schemas/PreLoadResponse'
    OperationResultCodeResponse:
      $ref: 'consolidatore-v1.yml#/components/schemas/OperationResultCodeResponse'
    PaperProgressStatusEvent:
      $ref: 'consolidatore-v1.yml#/components/schemas/PaperProgressStatusEvent'    